apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: spring-boot-k8s-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       spring-boot-k8s-deployment
  updatePolicy:
    updateMode: "Auto"  # Options: Off, Initial, Auto
  resourcePolicy:
    containerPolicies:
    - containerName: spring-boot-k8s
      controlledResources: ["cpu", "memory"]
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 1000m
        memory: 1Gi
